### ISSUE TITLE
onDestroy()  method doesn't save notes

### ISSUE THREAD

**Issue by dmytrobohdanov** [dmytrobohdanov/android_Notes#20]
error:
W/System.err: java.io.FileNotFoundException: /notes.out: open failed: EROFS (Read-only file system)
04-20 15:00:50.639 16097-16097/com.dmytro.notes19_2 W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:453)
04-20 15:00:50.639 16097-16097/com.dmytro.notes19_2 W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:88)
04-20 15:00:50.639 16097-16097/com.dmytro.notes19_2 W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:73)
04-20 15:00:50.639 16097-16097/com.dmytro.notes19_2 W/System.err:     at com.dmytro.notes19_2.DataSaver.saveArrayOfNotes(DataSaver.java:57)

**Comment by dmytrobohdanov** [comment]
fixed that error

there is still this problem..
